# Generated by Django 5.2.14 on 2026-06-02 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('source_type', models.CharField(choices=[('youtube', 'YouTube'), ('article', 'Article / Link'), ('x', 'X / Twitter'), ('text', 'Text'), ('image', 'Image')], default='article', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_content', models.TextField(blank=True)),
                ('cleaned_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='notes', to='notes.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('file', 'File')], default='image', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/')),
                ('remote_url', models.URLField(blank=True, max_length=2000)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notes.note')),
            ],
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['owner', '-created_at'], name='notes_note_owner_i_b6b830_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['status'], name='notes_note_status_8ff649_idx'),
        ),
    ]
