# Generated by Django 5.2.14 on 2026-06-03 14:37

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.contrib.postgres.search import SearchVector
from django.db import migrations


def backfill_search_vector(apps, schema_editor):
    Note = apps.get_model("notes", "Note")
    Note.objects.update(
        search_vector=(
            SearchVector("title", weight="A")
            + SearchVector("summary", weight="B")
            + SearchVector("cleaned_text", weight="C")
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='note',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='note_search_gin'),
        ),
        migrations.RunPython(backfill_search_vector, migrations.RunPython.noop),
    ]
